# This is a basic workflow to trigger packer buil on merge commit into main branch


name: Build Packer
on:
  pull_request:
    branches:
      - 'main'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: packer validate ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_USERS: ${{ secrets.AMI_USERS }}
          AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}

name: Run packer build
on:
  push:
    branches:
        - 'main'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: packer validate ami.json
      - run: packer build ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_USERS: ${{ secrets.AMI_USERS }}
          AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}