name: Run packer build

on: 
  pull_request:
   types: [closed]
    
jobs:
  build:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Build
        uses: actions/checkout@v2

      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: --syntax-only
          target: ami.json
          
      - name: Build Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          target: ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
