name: Run packer build
on: [ pull_request ]
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@main
        with:
          command: validate
          argumenrs: -syntax-only
          target: ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_USERS: ${{ secrets.AMI_USERS }}
          AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}